# Generated by Django 4.2.1 on 2023-07-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='montoTotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
